<?php
/**
 * SearchApi
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API
 *
 * OpenAPI spec version: 20250801.3_release
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infocenter\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Infocenter\Client\ApiException;
use Infocenter\Client\Configuration;
use Infocenter\Client\HeaderSelector;
use Infocenter\Client\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createView
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Infocenter\Client\Model\DsSearchViewResponse
     */
    public function createView($ocp_apim_subscription_key, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        list($response) = $this->createViewWithHttpInfo($ocp_apim_subscription_key, $body, $authorization, $accept_language, $accept_timezone, $category_version);
        return $response;
    }

    /**
     * Operation createViewWithHttpInfo
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Infocenter\Client\Model\DsSearchViewResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createViewWithHttpInfo($ocp_apim_subscription_key, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse';
        $request = $this->createViewRequest($ocp_apim_subscription_key, $body, $authorization, $accept_language, $accept_timezone, $category_version);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Infocenter\Client\Model\DsSearchViewResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createViewAsync
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createViewAsync($ocp_apim_subscription_key, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        return $this->createViewAsyncWithHttpInfo($ocp_apim_subscription_key, $body, $authorization, $accept_language, $accept_timezone, $category_version)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createViewAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createViewAsyncWithHttpInfo($ocp_apim_subscription_key, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse';
        $request = $this->createViewRequest($ocp_apim_subscription_key, $body, $authorization, $accept_language, $accept_timezone, $category_version);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createView'
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createViewRequest($ocp_apim_subscription_key, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        // verify the required parameter 'ocp_apim_subscription_key' is set
        if ($ocp_apim_subscription_key === null || (is_array($ocp_apim_subscription_key) && count($ocp_apim_subscription_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ocp_apim_subscription_key when calling createView'
            );
        }

        $resourcePath = '/search/views';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($ocp_apim_subscription_key !== null) {
            $headerParams['Ocp-Apim-Subscription-Key'] = ObjectSerializer::toHeaderValue($ocp_apim_subscription_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($accept_timezone !== null) {
            $headerParams['Accept-Timezone'] = ObjectSerializer::toHeaderValue($accept_timezone);
        }
        // header params
        if ($category_version !== null) {
            $headerParams['categoryVersion'] = ObjectSerializer::toHeaderValue($category_version);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteView
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteView($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $this->deleteViewWithHttpInfo($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version);
    }

    /**
     * Operation deleteViewWithHttpInfo
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteViewWithHttpInfo($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '';
        $request = $this->deleteViewRequest($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteViewAsync
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteViewAsync($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        return $this->deleteViewAsyncWithHttpInfo($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteViewAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteViewAsyncWithHttpInfo($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '';
        $request = $this->deleteViewRequest($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteView'
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteViewRequest($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        // verify the required parameter 'ocp_apim_subscription_key' is set
        if ($ocp_apim_subscription_key === null || (is_array($ocp_apim_subscription_key) && count($ocp_apim_subscription_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ocp_apim_subscription_key when calling deleteView'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteView'
            );
        }

        $resourcePath = '/search/views/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($ocp_apim_subscription_key !== null) {
            $headerParams['Ocp-Apim-Subscription-Key'] = ObjectSerializer::toHeaderValue($ocp_apim_subscription_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($accept_timezone !== null) {
            $headerParams['Accept-Timezone'] = ObjectSerializer::toHeaderValue($accept_timezone);
        }
        // header params
        if ($category_version !== null) {
            $headerParams['categoryVersion'] = ObjectSerializer::toHeaderValue($category_version);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllViews
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Infocenter\Client\Model\DsSearchViewResponse[]
     */
    public function getAllViews($ocp_apim_subscription_key, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        list($response) = $this->getAllViewsWithHttpInfo($ocp_apim_subscription_key, $authorization, $accept_language, $accept_timezone, $category_version);
        return $response;
    }

    /**
     * Operation getAllViewsWithHttpInfo
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Infocenter\Client\Model\DsSearchViewResponse[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllViewsWithHttpInfo($ocp_apim_subscription_key, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse[]';
        $request = $this->getAllViewsRequest($ocp_apim_subscription_key, $authorization, $accept_language, $accept_timezone, $category_version);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Infocenter\Client\Model\DsSearchViewResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllViewsAsync
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllViewsAsync($ocp_apim_subscription_key, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        return $this->getAllViewsAsyncWithHttpInfo($ocp_apim_subscription_key, $authorization, $accept_language, $accept_timezone, $category_version)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllViewsAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllViewsAsyncWithHttpInfo($ocp_apim_subscription_key, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse[]';
        $request = $this->getAllViewsRequest($ocp_apim_subscription_key, $authorization, $accept_language, $accept_timezone, $category_version);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllViews'
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllViewsRequest($ocp_apim_subscription_key, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        // verify the required parameter 'ocp_apim_subscription_key' is set
        if ($ocp_apim_subscription_key === null || (is_array($ocp_apim_subscription_key) && count($ocp_apim_subscription_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ocp_apim_subscription_key when calling getAllViews'
            );
        }

        $resourcePath = '/search/views';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($ocp_apim_subscription_key !== null) {
            $headerParams['Ocp-Apim-Subscription-Key'] = ObjectSerializer::toHeaderValue($ocp_apim_subscription_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($accept_timezone !== null) {
            $headerParams['Accept-Timezone'] = ObjectSerializer::toHeaderValue($accept_timezone);
        }
        // header params
        if ($category_version !== null) {
            $headerParams['categoryVersion'] = ObjectSerializer::toHeaderValue($category_version);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getViewById
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Infocenter\Client\Model\DsSearchViewResponse
     */
    public function getViewById($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        list($response) = $this->getViewByIdWithHttpInfo($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version);
        return $response;
    }

    /**
     * Operation getViewByIdWithHttpInfo
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Infocenter\Client\Model\DsSearchViewResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getViewByIdWithHttpInfo($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse';
        $request = $this->getViewByIdRequest($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Infocenter\Client\Model\DsSearchViewResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getViewByIdAsync
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getViewByIdAsync($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        return $this->getViewByIdAsyncWithHttpInfo($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getViewByIdAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getViewByIdAsyncWithHttpInfo($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse';
        $request = $this->getViewByIdRequest($ocp_apim_subscription_key, $id, $authorization, $accept_language, $accept_timezone, $category_version);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getViewById'
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getViewByIdRequest($ocp_apim_subscription_key, $id, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        // verify the required parameter 'ocp_apim_subscription_key' is set
        if ($ocp_apim_subscription_key === null || (is_array($ocp_apim_subscription_key) && count($ocp_apim_subscription_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ocp_apim_subscription_key when calling getViewById'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getViewById'
            );
        }

        $resourcePath = '/search/views/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($ocp_apim_subscription_key !== null) {
            $headerParams['Ocp-Apim-Subscription-Key'] = ObjectSerializer::toHeaderValue($ocp_apim_subscription_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($accept_timezone !== null) {
            $headerParams['Accept-Timezone'] = ObjectSerializer::toHeaderValue($accept_timezone);
        }
        // header params
        if ($category_version !== null) {
            $headerParams['categoryVersion'] = ObjectSerializer::toHeaderValue($category_version);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateView
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Infocenter\Client\Model\DsSearchViewResponse
     */
    public function updateView($ocp_apim_subscription_key, $id, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        list($response) = $this->updateViewWithHttpInfo($ocp_apim_subscription_key, $id, $body, $authorization, $accept_language, $accept_timezone, $category_version);
        return $response;
    }

    /**
     * Operation updateViewWithHttpInfo
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \Infocenter\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Infocenter\Client\Model\DsSearchViewResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateViewWithHttpInfo($ocp_apim_subscription_key, $id, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse';
        $request = $this->updateViewRequest($ocp_apim_subscription_key, $id, $body, $authorization, $accept_language, $accept_timezone, $category_version);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Infocenter\Client\Model\DsSearchViewResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateViewAsync
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateViewAsync($ocp_apim_subscription_key, $id, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        return $this->updateViewAsyncWithHttpInfo($ocp_apim_subscription_key, $id, $body, $authorization, $accept_language, $accept_timezone, $category_version)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateViewAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateViewAsyncWithHttpInfo($ocp_apim_subscription_key, $id, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        $returnType = '\Infocenter\Client\Model\DsSearchViewResponse';
        $request = $this->updateViewRequest($ocp_apim_subscription_key, $id, $body, $authorization, $accept_language, $accept_timezone, $category_version);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateView'
     *
     * @param  string $ocp_apim_subscription_key Subscription key to access the API. Get it on (Developer portal)[https://developer.discover.swiss]. (required)
     * @param  string $id Search view identifier. (required)
     * @param  \Infocenter\Client\Model\DsSearchViewRequest $body (optional)
     * @param  string $authorization Authorization header to identify the B2C user profile. (optional)
     * @param  string $accept_language Two-letter language code to get localized properties. (optional)
     * @param  string $accept_timezone Time zone ID to apply its offset to dates and time. (optional)
     * @param  string $category_version Filters categories by version. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateViewRequest($ocp_apim_subscription_key, $id, $body = null, $authorization = null, $accept_language = null, $accept_timezone = null, $category_version = null)
    {
        // verify the required parameter 'ocp_apim_subscription_key' is set
        if ($ocp_apim_subscription_key === null || (is_array($ocp_apim_subscription_key) && count($ocp_apim_subscription_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ocp_apim_subscription_key when calling updateView'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateView'
            );
        }

        $resourcePath = '/search/views/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($ocp_apim_subscription_key !== null) {
            $headerParams['Ocp-Apim-Subscription-Key'] = ObjectSerializer::toHeaderValue($ocp_apim_subscription_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($accept_timezone !== null) {
            $headerParams['Accept-Timezone'] = ObjectSerializer::toHeaderValue($accept_timezone);
        }
        // header params
        if ($category_version !== null) {
            $headerParams['categoryVersion'] = ObjectSerializer::toHeaderValue($category_version);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
