<?php
/**
 * DsIndexResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infocenter\Client\Model;

use \ArrayAccess;
use \Infocenter\Client\ObjectSerializer;

/**
 * DsIndexResponse Class Doc Comment
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DsIndexResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'IndexResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'oua_id' => 'int',
        'identifier' => 'string',
        'datasource' => 'string[]',
        'data_governance' => '\Infocenter\Client\Model\DsDataGovernance',
        'type' => 'string',
        'additional_type' => 'string',
        'additional_property' => '\Infocenter\Client\Model\DsPropertyValue[]',
        'address' => '\Infocenter\Client\Model\DsPostalAddress',
        'geo' => '\Infocenter\Client\Model\DsGeoCoordinates',
        'geo_destination' => '\Infocenter\Client\Model\DsGeoCoordinates',
        'opening_hours' => 'string',
        'image' => '\Infocenter\Client\Model\DsImageObjectSimplex',
        'name' => 'string',
        'disambiguating_description' => 'string',
        'description' => 'string',
        'contained_in_place' => 'string',
        'state' => 'string',
        'time' => 'int',
        'length' => 'double',
        'rating' => '\Infocenter\Client\Model\DsTourRating',
        'campaign_tag' => 'string[]',
        'profile_tag' => 'string[]',
        'schedule' => '\Infocenter\Client\Model\DsSchedule[]',
        'next_occurrence' => '\DateTime',
        'recurred_count' => 'int',
        'elevation' => '\Infocenter\Client\Model\DsElevation',
        'link' => '\Infocenter\Client\Model\DsLink[]',
        'auto_translated_data' => 'bool',
        'ticketing_contact' => 'string',
        'price_information' => 'string',
        'standard_price' => 'double',
        'potential_action' => '\Infocenter\Client\Model\DsAction[]',
        'organizer' => '\Infocenter\Client\Model\DsOrganization',
        'last_modified' => '\DateTime',
        'source_id' => 'string[]',
        'has_review' => 'string',
        'location' => 'string',
        'category' => 'string[]',
        'product_availability' => '\Infocenter\Client\Model\DsProductAvailabilityResponse[]',
        'star_rating' => '\Infocenter\Client\Model\DsRating',
        'context' => '\Infocenter\Client\Model\DsSearchContext'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'oua_id' => 'int32',
        'identifier' => null,
        'datasource' => null,
        'data_governance' => null,
        'type' => null,
        'additional_type' => null,
        'additional_property' => null,
        'address' => null,
        'geo' => null,
        'geo_destination' => null,
        'opening_hours' => null,
        'image' => null,
        'name' => null,
        'disambiguating_description' => null,
        'description' => null,
        'contained_in_place' => null,
        'state' => null,
        'time' => 'int32',
        'length' => 'double',
        'rating' => null,
        'campaign_tag' => null,
        'profile_tag' => null,
        'schedule' => null,
        'next_occurrence' => 'date-time',
        'recurred_count' => 'int32',
        'elevation' => null,
        'link' => null,
        'auto_translated_data' => null,
        'ticketing_contact' => null,
        'price_information' => null,
        'standard_price' => 'double',
        'potential_action' => null,
        'organizer' => null,
        'last_modified' => 'date-time',
        'source_id' => null,
        'has_review' => null,
        'location' => null,
        'category' => null,
        'product_availability' => null,
        'star_rating' => null,
        'context' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => '@id',
        'oua_id' => 'ouaId',
        'identifier' => 'identifier',
        'datasource' => 'datasource',
        'data_governance' => 'dataGovernance',
        'type' => 'type',
        'additional_type' => 'additionalType',
        'additional_property' => 'additionalProperty',
        'address' => 'address',
        'geo' => 'geo',
        'geo_destination' => 'geoDestination',
        'opening_hours' => 'openingHours',
        'image' => 'image',
        'name' => 'name',
        'disambiguating_description' => 'disambiguatingDescription',
        'description' => 'description',
        'contained_in_place' => 'containedInPlace',
        'state' => 'state',
        'time' => 'time',
        'length' => 'length',
        'rating' => 'rating',
        'campaign_tag' => 'campaignTag',
        'profile_tag' => 'profileTag',
        'schedule' => 'schedule',
        'next_occurrence' => 'nextOccurrence',
        'recurred_count' => 'recurredCount',
        'elevation' => 'elevation',
        'link' => 'link',
        'auto_translated_data' => 'autoTranslatedData',
        'ticketing_contact' => 'ticketingContact',
        'price_information' => 'priceInformation',
        'standard_price' => 'standardPrice',
        'potential_action' => 'potentialAction',
        'organizer' => 'organizer',
        'last_modified' => 'lastModified',
        'source_id' => 'sourceId',
        'has_review' => 'hasReview',
        'location' => 'location',
        'category' => 'category',
        'product_availability' => 'productAvailability',
        'star_rating' => 'starRating',
        'context' => 'context'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'oua_id' => 'setOuaId',
        'identifier' => 'setIdentifier',
        'datasource' => 'setDatasource',
        'data_governance' => 'setDataGovernance',
        'type' => 'setType',
        'additional_type' => 'setAdditionalType',
        'additional_property' => 'setAdditionalProperty',
        'address' => 'setAddress',
        'geo' => 'setGeo',
        'geo_destination' => 'setGeoDestination',
        'opening_hours' => 'setOpeningHours',
        'image' => 'setImage',
        'name' => 'setName',
        'disambiguating_description' => 'setDisambiguatingDescription',
        'description' => 'setDescription',
        'contained_in_place' => 'setContainedInPlace',
        'state' => 'setState',
        'time' => 'setTime',
        'length' => 'setLength',
        'rating' => 'setRating',
        'campaign_tag' => 'setCampaignTag',
        'profile_tag' => 'setProfileTag',
        'schedule' => 'setSchedule',
        'next_occurrence' => 'setNextOccurrence',
        'recurred_count' => 'setRecurredCount',
        'elevation' => 'setElevation',
        'link' => 'setLink',
        'auto_translated_data' => 'setAutoTranslatedData',
        'ticketing_contact' => 'setTicketingContact',
        'price_information' => 'setPriceInformation',
        'standard_price' => 'setStandardPrice',
        'potential_action' => 'setPotentialAction',
        'organizer' => 'setOrganizer',
        'last_modified' => 'setLastModified',
        'source_id' => 'setSourceId',
        'has_review' => 'setHasReview',
        'location' => 'setLocation',
        'category' => 'setCategory',
        'product_availability' => 'setProductAvailability',
        'star_rating' => 'setStarRating',
        'context' => 'setContext'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'oua_id' => 'getOuaId',
        'identifier' => 'getIdentifier',
        'datasource' => 'getDatasource',
        'data_governance' => 'getDataGovernance',
        'type' => 'getType',
        'additional_type' => 'getAdditionalType',
        'additional_property' => 'getAdditionalProperty',
        'address' => 'getAddress',
        'geo' => 'getGeo',
        'geo_destination' => 'getGeoDestination',
        'opening_hours' => 'getOpeningHours',
        'image' => 'getImage',
        'name' => 'getName',
        'disambiguating_description' => 'getDisambiguatingDescription',
        'description' => 'getDescription',
        'contained_in_place' => 'getContainedInPlace',
        'state' => 'getState',
        'time' => 'getTime',
        'length' => 'getLength',
        'rating' => 'getRating',
        'campaign_tag' => 'getCampaignTag',
        'profile_tag' => 'getProfileTag',
        'schedule' => 'getSchedule',
        'next_occurrence' => 'getNextOccurrence',
        'recurred_count' => 'getRecurredCount',
        'elevation' => 'getElevation',
        'link' => 'getLink',
        'auto_translated_data' => 'getAutoTranslatedData',
        'ticketing_contact' => 'getTicketingContact',
        'price_information' => 'getPriceInformation',
        'standard_price' => 'getStandardPrice',
        'potential_action' => 'getPotentialAction',
        'organizer' => 'getOrganizer',
        'last_modified' => 'getLastModified',
        'source_id' => 'getSourceId',
        'has_review' => 'getHasReview',
        'location' => 'getLocation',
        'category' => 'getCategory',
        'product_availability' => 'getProductAvailability',
        'star_rating' => 'getStarRating',
        'context' => 'getContext'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['oua_id'] = isset($data['oua_id']) ? $data['oua_id'] : null;
        $this->container['identifier'] = isset($data['identifier']) ? $data['identifier'] : null;
        $this->container['datasource'] = isset($data['datasource']) ? $data['datasource'] : null;
        $this->container['data_governance'] = isset($data['data_governance']) ? $data['data_governance'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['additional_type'] = isset($data['additional_type']) ? $data['additional_type'] : null;
        $this->container['additional_property'] = isset($data['additional_property']) ? $data['additional_property'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['geo'] = isset($data['geo']) ? $data['geo'] : null;
        $this->container['geo_destination'] = isset($data['geo_destination']) ? $data['geo_destination'] : null;
        $this->container['opening_hours'] = isset($data['opening_hours']) ? $data['opening_hours'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['disambiguating_description'] = isset($data['disambiguating_description']) ? $data['disambiguating_description'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['contained_in_place'] = isset($data['contained_in_place']) ? $data['contained_in_place'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
        $this->container['length'] = isset($data['length']) ? $data['length'] : null;
        $this->container['rating'] = isset($data['rating']) ? $data['rating'] : null;
        $this->container['campaign_tag'] = isset($data['campaign_tag']) ? $data['campaign_tag'] : null;
        $this->container['profile_tag'] = isset($data['profile_tag']) ? $data['profile_tag'] : null;
        $this->container['schedule'] = isset($data['schedule']) ? $data['schedule'] : null;
        $this->container['next_occurrence'] = isset($data['next_occurrence']) ? $data['next_occurrence'] : null;
        $this->container['recurred_count'] = isset($data['recurred_count']) ? $data['recurred_count'] : null;
        $this->container['elevation'] = isset($data['elevation']) ? $data['elevation'] : null;
        $this->container['link'] = isset($data['link']) ? $data['link'] : null;
        $this->container['auto_translated_data'] = isset($data['auto_translated_data']) ? $data['auto_translated_data'] : null;
        $this->container['ticketing_contact'] = isset($data['ticketing_contact']) ? $data['ticketing_contact'] : null;
        $this->container['price_information'] = isset($data['price_information']) ? $data['price_information'] : null;
        $this->container['standard_price'] = isset($data['standard_price']) ? $data['standard_price'] : null;
        $this->container['potential_action'] = isset($data['potential_action']) ? $data['potential_action'] : null;
        $this->container['organizer'] = isset($data['organizer']) ? $data['organizer'] : null;
        $this->container['last_modified'] = isset($data['last_modified']) ? $data['last_modified'] : null;
        $this->container['source_id'] = isset($data['source_id']) ? $data['source_id'] : null;
        $this->container['has_review'] = isset($data['has_review']) ? $data['has_review'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['product_availability'] = isset($data['product_availability']) ? $data['product_availability'] : null;
        $this->container['star_rating'] = isset($data['star_rating']) ? $data['star_rating'] : null;
        $this->container['context'] = isset($data['context']) ? $data['context'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id json-ld: full url to load the object (based on identifier)
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets oua_id
     *
     * @return int
     */
    public function getOuaId()
    {
        return $this->container['oua_id'];
    }

    /**
     * Sets oua_id
     *
     * @param int $oua_id Outdooractive id
     *
     * @return $this
     */
    public function setOuaId($oua_id)
    {
        $this->container['oua_id'] = $oua_id;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string $identifier identifier
     *
     * @return $this
     */
    public function setIdentifier($identifier)
    {
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets datasource
     *
     * @return string[]
     */
    public function getDatasource()
    {
        return $this->container['datasource'];
    }

    /**
     * Sets datasource
     *
     * @param string[] $datasource datasource
     *
     * @return $this
     */
    public function setDatasource($datasource)
    {
        $this->container['datasource'] = $datasource;

        return $this;
    }

    /**
     * Gets data_governance
     *
     * @return \Infocenter\Client\Model\DsDataGovernance
     */
    public function getDataGovernance()
    {
        return $this->container['data_governance'];
    }

    /**
     * Sets data_governance
     *
     * @param \Infocenter\Client\Model\DsDataGovernance $data_governance data_governance
     *
     * @return $this
     */
    public function setDataGovernance($data_governance)
    {
        $this->container['data_governance'] = $data_governance;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets additional_type
     *
     * @return string
     */
    public function getAdditionalType()
    {
        return $this->container['additional_type'];
    }

    /**
     * Sets additional_type
     *
     * @param string $additional_type additional_type
     *
     * @return $this
     */
    public function setAdditionalType($additional_type)
    {
        $this->container['additional_type'] = $additional_type;

        return $this;
    }

    /**
     * Gets additional_property
     *
     * @return \Infocenter\Client\Model\DsPropertyValue[]
     */
    public function getAdditionalProperty()
    {
        return $this->container['additional_property'];
    }

    /**
     * Sets additional_property
     *
     * @param \Infocenter\Client\Model\DsPropertyValue[] $additional_property additional_property
     *
     * @return $this
     */
    public function setAdditionalProperty($additional_property)
    {
        $this->container['additional_property'] = $additional_property;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \Infocenter\Client\Model\DsPostalAddress
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \Infocenter\Client\Model\DsPostalAddress $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets geo
     *
     * @return \Infocenter\Client\Model\DsGeoCoordinates
     */
    public function getGeo()
    {
        return $this->container['geo'];
    }

    /**
     * Sets geo
     *
     * @param \Infocenter\Client\Model\DsGeoCoordinates $geo geo
     *
     * @return $this
     */
    public function setGeo($geo)
    {
        $this->container['geo'] = $geo;

        return $this;
    }

    /**
     * Gets geo_destination
     *
     * @return \Infocenter\Client\Model\DsGeoCoordinates
     */
    public function getGeoDestination()
    {
        return $this->container['geo_destination'];
    }

    /**
     * Sets geo_destination
     *
     * @param \Infocenter\Client\Model\DsGeoCoordinates $geo_destination geo_destination
     *
     * @return $this
     */
    public function setGeoDestination($geo_destination)
    {
        $this->container['geo_destination'] = $geo_destination;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return string
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param string $opening_hours opening_hours
     *
     * @return $this
     */
    public function setOpeningHours($opening_hours)
    {
        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \Infocenter\Client\Model\DsImageObjectSimplex
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \Infocenter\Client\Model\DsImageObjectSimplex $image image
     *
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets disambiguating_description
     *
     * @return string
     */
    public function getDisambiguatingDescription()
    {
        return $this->container['disambiguating_description'];
    }

    /**
     * Sets disambiguating_description
     *
     * @param string $disambiguating_description disambiguating_description
     *
     * @return $this
     */
    public function setDisambiguatingDescription($disambiguating_description)
    {
        $this->container['disambiguating_description'] = $disambiguating_description;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets contained_in_place
     *
     * @return string
     */
    public function getContainedInPlace()
    {
        return $this->container['contained_in_place'];
    }

    /**
     * Sets contained_in_place
     *
     * @param string $contained_in_place contained_in_place
     *
     * @return $this
     */
    public function setContainedInPlace($contained_in_place)
    {
        $this->container['contained_in_place'] = $contained_in_place;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state Tour state
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets time
     *
     * @return int
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param int $time Tour time
     *
     * @return $this
     */
    public function setTime($time)
    {
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets length
     *
     * @return double
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param double $length Tour length
     *
     * @return $this
     */
    public function setLength($length)
    {
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return \Infocenter\Client\Model\DsTourRating
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param \Infocenter\Client\Model\DsTourRating $rating rating
     *
     * @return $this
     */
    public function setRating($rating)
    {
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets campaign_tag
     *
     * @return string[]
     */
    public function getCampaignTag()
    {
        return $this->container['campaign_tag'];
    }

    /**
     * Sets campaign_tag
     *
     * @param string[] $campaign_tag campaign_tag
     *
     * @return $this
     */
    public function setCampaignTag($campaign_tag)
    {
        $this->container['campaign_tag'] = $campaign_tag;

        return $this;
    }

    /**
     * Gets profile_tag
     *
     * @return string[]
     */
    public function getProfileTag()
    {
        return $this->container['profile_tag'];
    }

    /**
     * Sets profile_tag
     *
     * @param string[] $profile_tag profile_tag
     *
     * @return $this
     */
    public function setProfileTag($profile_tag)
    {
        $this->container['profile_tag'] = $profile_tag;

        return $this;
    }

    /**
     * Gets schedule
     *
     * @return \Infocenter\Client\Model\DsSchedule[]
     */
    public function getSchedule()
    {
        return $this->container['schedule'];
    }

    /**
     * Sets schedule
     *
     * @param \Infocenter\Client\Model\DsSchedule[] $schedule schedule
     *
     * @return $this
     */
    public function setSchedule($schedule)
    {
        $this->container['schedule'] = $schedule;

        return $this;
    }

    /**
     * Gets next_occurrence
     *
     * @return \DateTime
     */
    public function getNextOccurrence()
    {
        return $this->container['next_occurrence'];
    }

    /**
     * Sets next_occurrence
     *
     * @param \DateTime $next_occurrence Contains the date and time of next occurrence of event
     *
     * @return $this
     */
    public function setNextOccurrence($next_occurrence)
    {
        $this->container['next_occurrence'] = $next_occurrence;

        return $this;
    }

    /**
     * Gets recurred_count
     *
     * @return int
     */
    public function getRecurredCount()
    {
        return $this->container['recurred_count'];
    }

    /**
     * Sets recurred_count
     *
     * @param int $recurred_count Contains the number of repetition of event with one week frequency
     *
     * @return $this
     */
    public function setRecurredCount($recurred_count)
    {
        $this->container['recurred_count'] = $recurred_count;

        return $this;
    }

    /**
     * Gets elevation
     *
     * @return \Infocenter\Client\Model\DsElevation
     */
    public function getElevation()
    {
        return $this->container['elevation'];
    }

    /**
     * Sets elevation
     *
     * @param \Infocenter\Client\Model\DsElevation $elevation elevation
     *
     * @return $this
     */
    public function setElevation($elevation)
    {
        $this->container['elevation'] = $elevation;

        return $this;
    }

    /**
     * Gets link
     *
     * @return \Infocenter\Client\Model\DsLink[]
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param \Infocenter\Client\Model\DsLink[] $link link
     *
     * @return $this
     */
    public function setLink($link)
    {
        $this->container['link'] = $link;

        return $this;
    }

    /**
     * Gets auto_translated_data
     *
     * @return bool
     */
    public function getAutoTranslatedData()
    {
        return $this->container['auto_translated_data'];
    }

    /**
     * Sets auto_translated_data
     *
     * @param bool $auto_translated_data Indicates if one of the text properties was translated by machine.
     *
     * @return $this
     */
    public function setAutoTranslatedData($auto_translated_data)
    {
        $this->container['auto_translated_data'] = $auto_translated_data;

        return $this;
    }

    /**
     * Gets ticketing_contact
     *
     * @return string
     */
    public function getTicketingContact()
    {
        return $this->container['ticketing_contact'];
    }

    /**
     * Sets ticketing_contact
     *
     * @param string $ticketing_contact ticketing_contact
     *
     * @return $this
     */
    public function setTicketingContact($ticketing_contact)
    {
        $this->container['ticketing_contact'] = $ticketing_contact;

        return $this;
    }

    /**
     * Gets price_information
     *
     * @return string
     */
    public function getPriceInformation()
    {
        return $this->container['price_information'];
    }

    /**
     * Sets price_information
     *
     * @param string $price_information price_information
     *
     * @return $this
     */
    public function setPriceInformation($price_information)
    {
        $this->container['price_information'] = $price_information;

        return $this;
    }

    /**
     * Gets standard_price
     *
     * @return double
     */
    public function getStandardPrice()
    {
        return $this->container['standard_price'];
    }

    /**
     * Sets standard_price
     *
     * @param double $standard_price standard_price
     *
     * @return $this
     */
    public function setStandardPrice($standard_price)
    {
        $this->container['standard_price'] = $standard_price;

        return $this;
    }

    /**
     * Gets potential_action
     *
     * @return \Infocenter\Client\Model\DsAction[]
     */
    public function getPotentialAction()
    {
        return $this->container['potential_action'];
    }

    /**
     * Sets potential_action
     *
     * @param \Infocenter\Client\Model\DsAction[] $potential_action potential_action
     *
     * @return $this
     */
    public function setPotentialAction($potential_action)
    {
        $this->container['potential_action'] = $potential_action;

        return $this;
    }

    /**
     * Gets organizer
     *
     * @return \Infocenter\Client\Model\DsOrganization
     */
    public function getOrganizer()
    {
        return $this->container['organizer'];
    }

    /**
     * Sets organizer
     *
     * @param \Infocenter\Client\Model\DsOrganization $organizer organizer
     *
     * @return $this
     */
    public function setOrganizer($organizer)
    {
        $this->container['organizer'] = $organizer;

        return $this;
    }

    /**
     * Gets last_modified
     *
     * @return \DateTime
     */
    public function getLastModified()
    {
        return $this->container['last_modified'];
    }

    /**
     * Sets last_modified
     *
     * @param \DateTime $last_modified last_modified
     *
     * @return $this
     */
    public function setLastModified($last_modified)
    {
        $this->container['last_modified'] = $last_modified;

        return $this;
    }

    /**
     * Gets source_id
     *
     * @return string[]
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param string[] $source_id source_id
     *
     * @return $this
     */
    public function setSourceId($source_id)
    {
        $this->container['source_id'] = $source_id;

        return $this;
    }

    /**
     * Gets has_review
     *
     * @return string
     */
    public function getHasReview()
    {
        return $this->container['has_review'];
    }

    /**
     * Sets has_review
     *
     * @param string $has_review true or false if the object contains reviews
     *
     * @return $this
     */
    public function setHasReview($has_review)
    {
        $this->container['has_review'] = $has_review;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string[]
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string[] $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets product_availability
     *
     * @return \Infocenter\Client\Model\DsProductAvailabilityResponse[]
     */
    public function getProductAvailability()
    {
        return $this->container['product_availability'];
    }

    /**
     * Sets product_availability
     *
     * @param \Infocenter\Client\Model\DsProductAvailabilityResponse[] $product_availability product_availability
     *
     * @return $this
     */
    public function setProductAvailability($product_availability)
    {
        $this->container['product_availability'] = $product_availability;

        return $this;
    }

    /**
     * Gets star_rating
     *
     * @return \Infocenter\Client\Model\DsRating
     */
    public function getStarRating()
    {
        return $this->container['star_rating'];
    }

    /**
     * Sets star_rating
     *
     * @param \Infocenter\Client\Model\DsRating $star_rating star_rating
     *
     * @return $this
     */
    public function setStarRating($star_rating)
    {
        $this->container['star_rating'] = $star_rating;

        return $this;
    }

    /**
     * Gets context
     *
     * @return \Infocenter\Client\Model\DsSearchContext
     */
    public function getContext()
    {
        return $this->container['context'];
    }

    /**
     * Sets context
     *
     * @param \Infocenter\Client\Model\DsSearchContext $context context
     *
     * @return $this
     */
    public function setContext($context)
    {
        $this->container['context'] = $context;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
