<?php
/**
 * DsProductPrice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Infocenter\Client\Model;

use \ArrayAccess;
use \Infocenter\Client\ObjectSerializer;

/**
 * DsProductPrice Class Doc Comment
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DsProductPrice implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProductPrice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'price_category_id' => 'string',
'price_category_name' => 'string',
'price_category_type' => 'string',
'price_chf' => 'double',
'compare_at_price_chf' => 'double',
'max_allowed_age' => 'int',
'min_allowed_age' => 'int',
'type' => 'string',
'min_seats' => 'int',
'max_seats' => 'int',
'valid_from' => '\DateTime',
'valid_through' => '\DateTime',
'reduction' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'price_category_id' => null,
'price_category_name' => null,
'price_category_type' => null,
'price_chf' => 'double',
'compare_at_price_chf' => 'double',
'max_allowed_age' => 'int32',
'min_allowed_age' => 'int32',
'type' => null,
'min_seats' => 'int32',
'max_seats' => 'int32',
'valid_from' => 'date-time',
'valid_through' => 'date-time',
'reduction' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'price_category_id' => 'priceCategoryId',
'price_category_name' => 'priceCategoryName',
'price_category_type' => 'priceCategoryType',
'price_chf' => 'priceCHF',
'compare_at_price_chf' => 'compareAtPriceCHF',
'max_allowed_age' => 'maxAllowedAge',
'min_allowed_age' => 'minAllowedAge',
'type' => 'type',
'min_seats' => 'minSeats',
'max_seats' => 'maxSeats',
'valid_from' => 'validFrom',
'valid_through' => 'validThrough',
'reduction' => 'reduction'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'price_category_id' => 'setPriceCategoryId',
'price_category_name' => 'setPriceCategoryName',
'price_category_type' => 'setPriceCategoryType',
'price_chf' => 'setPriceChf',
'compare_at_price_chf' => 'setCompareAtPriceChf',
'max_allowed_age' => 'setMaxAllowedAge',
'min_allowed_age' => 'setMinAllowedAge',
'type' => 'setType',
'min_seats' => 'setMinSeats',
'max_seats' => 'setMaxSeats',
'valid_from' => 'setValidFrom',
'valid_through' => 'setValidThrough',
'reduction' => 'setReduction'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'price_category_id' => 'getPriceCategoryId',
'price_category_name' => 'getPriceCategoryName',
'price_category_type' => 'getPriceCategoryType',
'price_chf' => 'getPriceChf',
'compare_at_price_chf' => 'getCompareAtPriceChf',
'max_allowed_age' => 'getMaxAllowedAge',
'min_allowed_age' => 'getMinAllowedAge',
'type' => 'getType',
'min_seats' => 'getMinSeats',
'max_seats' => 'getMaxSeats',
'valid_from' => 'getValidFrom',
'valid_through' => 'getValidThrough',
'reduction' => 'getReduction'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['price_category_id'] = isset($data['price_category_id']) ? $data['price_category_id'] : null;
        $this->container['price_category_name'] = isset($data['price_category_name']) ? $data['price_category_name'] : null;
        $this->container['price_category_type'] = isset($data['price_category_type']) ? $data['price_category_type'] : null;
        $this->container['price_chf'] = isset($data['price_chf']) ? $data['price_chf'] : null;
        $this->container['compare_at_price_chf'] = isset($data['compare_at_price_chf']) ? $data['compare_at_price_chf'] : null;
        $this->container['max_allowed_age'] = isset($data['max_allowed_age']) ? $data['max_allowed_age'] : null;
        $this->container['min_allowed_age'] = isset($data['min_allowed_age']) ? $data['min_allowed_age'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['min_seats'] = isset($data['min_seats']) ? $data['min_seats'] : null;
        $this->container['max_seats'] = isset($data['max_seats']) ? $data['max_seats'] : null;
        $this->container['valid_from'] = isset($data['valid_from']) ? $data['valid_from'] : null;
        $this->container['valid_through'] = isset($data['valid_through']) ? $data['valid_through'] : null;
        $this->container['reduction'] = isset($data['reduction']) ? $data['reduction'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets price_category_id
     *
     * @return string
     */
    public function getPriceCategoryId()
    {
        return $this->container['price_category_id'];
    }

    /**
     * Sets price_category_id
     *
     * @param string $price_category_id price_category_id
     *
     * @return $this
     */
    public function setPriceCategoryId($price_category_id)
    {
        $this->container['price_category_id'] = $price_category_id;

        return $this;
    }

    /**
     * Gets price_category_name
     *
     * @return string
     */
    public function getPriceCategoryName()
    {
        return $this->container['price_category_name'];
    }

    /**
     * Sets price_category_name
     *
     * @param string $price_category_name price_category_name
     *
     * @return $this
     */
    public function setPriceCategoryName($price_category_name)
    {
        $this->container['price_category_name'] = $price_category_name;

        return $this;
    }

    /**
     * Gets price_category_type
     *
     * @return string
     */
    public function getPriceCategoryType()
    {
        return $this->container['price_category_type'];
    }

    /**
     * Sets price_category_type
     *
     * @param string $price_category_type price_category_type
     *
     * @return $this
     */
    public function setPriceCategoryType($price_category_type)
    {
        $this->container['price_category_type'] = $price_category_type;

        return $this;
    }

    /**
     * Gets price_chf
     *
     * @return double
     */
    public function getPriceChf()
    {
        return $this->container['price_chf'];
    }

    /**
     * Sets price_chf
     *
     * @param double $price_chf price_chf
     *
     * @return $this
     */
    public function setPriceChf($price_chf)
    {
        $this->container['price_chf'] = $price_chf;

        return $this;
    }

    /**
     * Gets compare_at_price_chf
     *
     * @return double
     */
    public function getCompareAtPriceChf()
    {
        return $this->container['compare_at_price_chf'];
    }

    /**
     * Sets compare_at_price_chf
     *
     * @param double $compare_at_price_chf compare_at_price_chf
     *
     * @return $this
     */
    public function setCompareAtPriceChf($compare_at_price_chf)
    {
        $this->container['compare_at_price_chf'] = $compare_at_price_chf;

        return $this;
    }

    /**
     * Gets max_allowed_age
     *
     * @return int
     */
    public function getMaxAllowedAge()
    {
        return $this->container['max_allowed_age'];
    }

    /**
     * Sets max_allowed_age
     *
     * @param int $max_allowed_age max_allowed_age
     *
     * @return $this
     */
    public function setMaxAllowedAge($max_allowed_age)
    {
        $this->container['max_allowed_age'] = $max_allowed_age;

        return $this;
    }

    /**
     * Gets min_allowed_age
     *
     * @return int
     */
    public function getMinAllowedAge()
    {
        return $this->container['min_allowed_age'];
    }

    /**
     * Sets min_allowed_age
     *
     * @param int $min_allowed_age min_allowed_age
     *
     * @return $this
     */
    public function setMinAllowedAge($min_allowed_age)
    {
        $this->container['min_allowed_age'] = $min_allowed_age;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets min_seats
     *
     * @return int
     */
    public function getMinSeats()
    {
        return $this->container['min_seats'];
    }

    /**
     * Sets min_seats
     *
     * @param int $min_seats min_seats
     *
     * @return $this
     */
    public function setMinSeats($min_seats)
    {
        $this->container['min_seats'] = $min_seats;

        return $this;
    }

    /**
     * Gets max_seats
     *
     * @return int
     */
    public function getMaxSeats()
    {
        return $this->container['max_seats'];
    }

    /**
     * Sets max_seats
     *
     * @param int $max_seats max_seats
     *
     * @return $this
     */
    public function setMaxSeats($max_seats)
    {
        $this->container['max_seats'] = $max_seats;

        return $this;
    }

    /**
     * Gets valid_from
     *
     * @return \DateTime
     */
    public function getValidFrom()
    {
        return $this->container['valid_from'];
    }

    /**
     * Sets valid_from
     *
     * @param \DateTime $valid_from valid_from
     *
     * @return $this
     */
    public function setValidFrom($valid_from)
    {
        $this->container['valid_from'] = $valid_from;

        return $this;
    }

    /**
     * Gets valid_through
     *
     * @return \DateTime
     */
    public function getValidThrough()
    {
        return $this->container['valid_through'];
    }

    /**
     * Sets valid_through
     *
     * @param \DateTime $valid_through valid_through
     *
     * @return $this
     */
    public function setValidThrough($valid_through)
    {
        $this->container['valid_through'] = $valid_through;

        return $this;
    }

    /**
     * Gets reduction
     *
     * @return string
     */
    public function getReduction()
    {
        return $this->container['reduction'];
    }

    /**
     * Sets reduction
     *
     * @param string $reduction reduction
     *
     * @return $this
     */
    public function setReduction($reduction)
    {
        $this->container['reduction'] = $reduction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
