<?php
/**
 * Tour
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST
 *
 * Infocenter-TEST
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Tour Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Tour implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Tour';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'winter_activity' => 'bool',
'length' => 'double',
'time' => 'int',
'elevation_json' => 'object',
'rating_json' => 'object',
'season_json' => 'object',
'difficulties_json' => 'object',
'exposition_json' => 'object',
'risk_potential' => 'int',
'titles' => 'string',
'starting_point_description' => 'string',
'safety_guidelines' => 'string',
'equipment' => 'string',
'tip' => 'string',
'additional_information' => 'string',
'destination' => 'string',
'track_signage' => 'string',
'literature' => 'string',
'maps' => 'string',
'state' => 'string',
'available_language' => 'string[]',
'address' => '\Swagger\Client\Model\AdministrativeAreaAddress',
'fax_number' => 'string',
'geo' => '\Swagger\Client\Model\AdministrativeAreaGeo',
'has_map' => 'string',
'is_accessible_for_free' => 'bool',
'maximum_attendee_capacity' => 'int',
'opening_hours_specification' => '\Swagger\Client\Model\AdministrativeAreaAddressHoursAvailable[]',
'photo' => '\Swagger\Client\Model\AdministrativeAreaAddressImage[]',
'public_access' => 'bool',
'smoking_allowed' => 'bool',
'source' => '\Swagger\Client\Model\AdministrativeAreaAddressSource',
'special_opening_hours_specification' => '\Swagger\Client\Model\AdministrativeAreaAddressHoursAvailable[]',
'telephone' => 'string',
'tourist_type' => 'string',
'additional_property' => '\Swagger\Client\Model\AdministrativeAreaAdditionalProperty[]',
'geo_shape' => '\Swagger\Client\Model\AdministrativeAreaGeoShape',
'cc' => 'string',
'located' => 'string[]',
'copyright' => 'string',
'detailed_information' => 'string[]',
'title_teaser' => 'string',
'text_teaser' => 'string',
'public_transport' => 'string',
'getting_there' => 'string',
'parking' => 'string',
'directions' => 'string',
'fees' => 'string',
'zurichcard' => 'string',
'zurichcard_description' => 'string',
'osm_id' => 'string',
'aggregate_rating' => '\Swagger\Client\Model\AdministrativeAreaAggregateRating',
'type' => 'string',
'opening_hours' => 'string',
'category' => '\Swagger\Client\Model\AdministrativeAreaAddressLabels[]',
'contained_in_place' => '\Swagger\Client\Model\AdministrativeAreaAddressLabels[]',
'id' => 'string',
'identifier' => 'string',
'datasource' => 'string',
'data_governance' => '\Swagger\Client\Model\AdministrativeAreaAddressImageDataGovernance',
'alternate_name' => 'string',
'description' => 'string',
'disambiguating_description' => 'string',
'image' => '\Swagger\Client\Model\AdministrativeAreaAddressImage',
'same_as' => 'string',
'url' => 'string',
'additional_type' => 'string',
'links' => '\Swagger\Client\Model\AdministrativeAreaAddressImageDataGovernanceSourceLink[]',
'labels' => '\Swagger\Client\Model\AdministrativeAreaAddressLabels[]',
'name' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'winter_activity' => null,
'length' => 'double',
'time' => 'int32',
'elevation_json' => null,
'rating_json' => null,
'season_json' => null,
'difficulties_json' => null,
'exposition_json' => null,
'risk_potential' => 'int32',
'titles' => null,
'starting_point_description' => null,
'safety_guidelines' => null,
'equipment' => null,
'tip' => null,
'additional_information' => null,
'destination' => null,
'track_signage' => null,
'literature' => null,
'maps' => null,
'state' => null,
'available_language' => null,
'address' => null,
'fax_number' => null,
'geo' => null,
'has_map' => null,
'is_accessible_for_free' => null,
'maximum_attendee_capacity' => 'int32',
'opening_hours_specification' => null,
'photo' => null,
'public_access' => null,
'smoking_allowed' => null,
'source' => null,
'special_opening_hours_specification' => null,
'telephone' => null,
'tourist_type' => null,
'additional_property' => null,
'geo_shape' => null,
'cc' => null,
'located' => null,
'copyright' => null,
'detailed_information' => null,
'title_teaser' => null,
'text_teaser' => null,
'public_transport' => null,
'getting_there' => null,
'parking' => null,
'directions' => null,
'fees' => null,
'zurichcard' => null,
'zurichcard_description' => null,
'osm_id' => null,
'aggregate_rating' => null,
'type' => null,
'opening_hours' => null,
'category' => null,
'contained_in_place' => null,
'id' => null,
'identifier' => null,
'datasource' => null,
'data_governance' => null,
'alternate_name' => null,
'description' => null,
'disambiguating_description' => null,
'image' => null,
'same_as' => null,
'url' => null,
'additional_type' => null,
'links' => null,
'labels' => null,
'name' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'winter_activity' => 'winterActivity',
'length' => 'length',
'time' => 'time',
'elevation_json' => 'elevationJson',
'rating_json' => 'ratingJson',
'season_json' => 'seasonJson',
'difficulties_json' => 'difficultiesJson',
'exposition_json' => 'expositionJson',
'risk_potential' => 'riskPotential',
'titles' => 'titles',
'starting_point_description' => 'startingPointDescription',
'safety_guidelines' => 'safetyGuidelines',
'equipment' => 'equipment',
'tip' => 'tip',
'additional_information' => 'additionalInformation',
'destination' => 'destination',
'track_signage' => 'trackSignage',
'literature' => 'literature',
'maps' => 'maps',
'state' => 'state',
'available_language' => 'availableLanguage',
'address' => 'address',
'fax_number' => 'faxNumber',
'geo' => 'geo',
'has_map' => 'hasMap',
'is_accessible_for_free' => 'isAccessibleForFree',
'maximum_attendee_capacity' => 'maximumAttendeeCapacity',
'opening_hours_specification' => 'openingHoursSpecification',
'photo' => 'photo',
'public_access' => 'publicAccess',
'smoking_allowed' => 'smokingAllowed',
'source' => 'source',
'special_opening_hours_specification' => 'specialOpeningHoursSpecification',
'telephone' => 'telephone',
'tourist_type' => 'touristType',
'additional_property' => 'additionalProperty',
'geo_shape' => 'geoShape',
'cc' => 'cc',
'located' => 'located',
'copyright' => 'copyright',
'detailed_information' => 'detailedInformation',
'title_teaser' => 'titleTeaser',
'text_teaser' => 'textTeaser',
'public_transport' => 'publicTransport',
'getting_there' => 'gettingThere',
'parking' => 'parking',
'directions' => 'directions',
'fees' => 'fees',
'zurichcard' => 'zurichcard',
'zurichcard_description' => 'zurichcardDescription',
'osm_id' => 'osm_id',
'aggregate_rating' => 'aggregateRating',
'type' => 'type',
'opening_hours' => 'openingHours',
'category' => 'category',
'contained_in_place' => 'containedInPlace',
'id' => '@id',
'identifier' => 'identifier',
'datasource' => 'datasource',
'data_governance' => 'dataGovernance',
'alternate_name' => 'alternateName',
'description' => 'description',
'disambiguating_description' => 'disambiguatingDescription',
'image' => 'image',
'same_as' => 'sameAs',
'url' => 'url',
'additional_type' => 'additionalType',
'links' => 'links',
'labels' => 'labels',
'name' => 'name'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'winter_activity' => 'setWinterActivity',
'length' => 'setLength',
'time' => 'setTime',
'elevation_json' => 'setElevationJson',
'rating_json' => 'setRatingJson',
'season_json' => 'setSeasonJson',
'difficulties_json' => 'setDifficultiesJson',
'exposition_json' => 'setExpositionJson',
'risk_potential' => 'setRiskPotential',
'titles' => 'setTitles',
'starting_point_description' => 'setStartingPointDescription',
'safety_guidelines' => 'setSafetyGuidelines',
'equipment' => 'setEquipment',
'tip' => 'setTip',
'additional_information' => 'setAdditionalInformation',
'destination' => 'setDestination',
'track_signage' => 'setTrackSignage',
'literature' => 'setLiterature',
'maps' => 'setMaps',
'state' => 'setState',
'available_language' => 'setAvailableLanguage',
'address' => 'setAddress',
'fax_number' => 'setFaxNumber',
'geo' => 'setGeo',
'has_map' => 'setHasMap',
'is_accessible_for_free' => 'setIsAccessibleForFree',
'maximum_attendee_capacity' => 'setMaximumAttendeeCapacity',
'opening_hours_specification' => 'setOpeningHoursSpecification',
'photo' => 'setPhoto',
'public_access' => 'setPublicAccess',
'smoking_allowed' => 'setSmokingAllowed',
'source' => 'setSource',
'special_opening_hours_specification' => 'setSpecialOpeningHoursSpecification',
'telephone' => 'setTelephone',
'tourist_type' => 'setTouristType',
'additional_property' => 'setAdditionalProperty',
'geo_shape' => 'setGeoShape',
'cc' => 'setCc',
'located' => 'setLocated',
'copyright' => 'setCopyright',
'detailed_information' => 'setDetailedInformation',
'title_teaser' => 'setTitleTeaser',
'text_teaser' => 'setTextTeaser',
'public_transport' => 'setPublicTransport',
'getting_there' => 'setGettingThere',
'parking' => 'setParking',
'directions' => 'setDirections',
'fees' => 'setFees',
'zurichcard' => 'setZurichcard',
'zurichcard_description' => 'setZurichcardDescription',
'osm_id' => 'setOsmId',
'aggregate_rating' => 'setAggregateRating',
'type' => 'setType',
'opening_hours' => 'setOpeningHours',
'category' => 'setCategory',
'contained_in_place' => 'setContainedInPlace',
'id' => 'setId',
'identifier' => 'setIdentifier',
'datasource' => 'setDatasource',
'data_governance' => 'setDataGovernance',
'alternate_name' => 'setAlternateName',
'description' => 'setDescription',
'disambiguating_description' => 'setDisambiguatingDescription',
'image' => 'setImage',
'same_as' => 'setSameAs',
'url' => 'setUrl',
'additional_type' => 'setAdditionalType',
'links' => 'setLinks',
'labels' => 'setLabels',
'name' => 'setName'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'winter_activity' => 'getWinterActivity',
'length' => 'getLength',
'time' => 'getTime',
'elevation_json' => 'getElevationJson',
'rating_json' => 'getRatingJson',
'season_json' => 'getSeasonJson',
'difficulties_json' => 'getDifficultiesJson',
'exposition_json' => 'getExpositionJson',
'risk_potential' => 'getRiskPotential',
'titles' => 'getTitles',
'starting_point_description' => 'getStartingPointDescription',
'safety_guidelines' => 'getSafetyGuidelines',
'equipment' => 'getEquipment',
'tip' => 'getTip',
'additional_information' => 'getAdditionalInformation',
'destination' => 'getDestination',
'track_signage' => 'getTrackSignage',
'literature' => 'getLiterature',
'maps' => 'getMaps',
'state' => 'getState',
'available_language' => 'getAvailableLanguage',
'address' => 'getAddress',
'fax_number' => 'getFaxNumber',
'geo' => 'getGeo',
'has_map' => 'getHasMap',
'is_accessible_for_free' => 'getIsAccessibleForFree',
'maximum_attendee_capacity' => 'getMaximumAttendeeCapacity',
'opening_hours_specification' => 'getOpeningHoursSpecification',
'photo' => 'getPhoto',
'public_access' => 'getPublicAccess',
'smoking_allowed' => 'getSmokingAllowed',
'source' => 'getSource',
'special_opening_hours_specification' => 'getSpecialOpeningHoursSpecification',
'telephone' => 'getTelephone',
'tourist_type' => 'getTouristType',
'additional_property' => 'getAdditionalProperty',
'geo_shape' => 'getGeoShape',
'cc' => 'getCc',
'located' => 'getLocated',
'copyright' => 'getCopyright',
'detailed_information' => 'getDetailedInformation',
'title_teaser' => 'getTitleTeaser',
'text_teaser' => 'getTextTeaser',
'public_transport' => 'getPublicTransport',
'getting_there' => 'getGettingThere',
'parking' => 'getParking',
'directions' => 'getDirections',
'fees' => 'getFees',
'zurichcard' => 'getZurichcard',
'zurichcard_description' => 'getZurichcardDescription',
'osm_id' => 'getOsmId',
'aggregate_rating' => 'getAggregateRating',
'type' => 'getType',
'opening_hours' => 'getOpeningHours',
'category' => 'getCategory',
'contained_in_place' => 'getContainedInPlace',
'id' => 'getId',
'identifier' => 'getIdentifier',
'datasource' => 'getDatasource',
'data_governance' => 'getDataGovernance',
'alternate_name' => 'getAlternateName',
'description' => 'getDescription',
'disambiguating_description' => 'getDisambiguatingDescription',
'image' => 'getImage',
'same_as' => 'getSameAs',
'url' => 'getUrl',
'additional_type' => 'getAdditionalType',
'links' => 'getLinks',
'labels' => 'getLabels',
'name' => 'getName'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['winter_activity'] = isset($data['winter_activity']) ? $data['winter_activity'] : null;
        $this->container['length'] = isset($data['length']) ? $data['length'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
        $this->container['elevation_json'] = isset($data['elevation_json']) ? $data['elevation_json'] : null;
        $this->container['rating_json'] = isset($data['rating_json']) ? $data['rating_json'] : null;
        $this->container['season_json'] = isset($data['season_json']) ? $data['season_json'] : null;
        $this->container['difficulties_json'] = isset($data['difficulties_json']) ? $data['difficulties_json'] : null;
        $this->container['exposition_json'] = isset($data['exposition_json']) ? $data['exposition_json'] : null;
        $this->container['risk_potential'] = isset($data['risk_potential']) ? $data['risk_potential'] : null;
        $this->container['titles'] = isset($data['titles']) ? $data['titles'] : null;
        $this->container['starting_point_description'] = isset($data['starting_point_description']) ? $data['starting_point_description'] : null;
        $this->container['safety_guidelines'] = isset($data['safety_guidelines']) ? $data['safety_guidelines'] : null;
        $this->container['equipment'] = isset($data['equipment']) ? $data['equipment'] : null;
        $this->container['tip'] = isset($data['tip']) ? $data['tip'] : null;
        $this->container['additional_information'] = isset($data['additional_information']) ? $data['additional_information'] : null;
        $this->container['destination'] = isset($data['destination']) ? $data['destination'] : null;
        $this->container['track_signage'] = isset($data['track_signage']) ? $data['track_signage'] : null;
        $this->container['literature'] = isset($data['literature']) ? $data['literature'] : null;
        $this->container['maps'] = isset($data['maps']) ? $data['maps'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['available_language'] = isset($data['available_language']) ? $data['available_language'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['fax_number'] = isset($data['fax_number']) ? $data['fax_number'] : null;
        $this->container['geo'] = isset($data['geo']) ? $data['geo'] : null;
        $this->container['has_map'] = isset($data['has_map']) ? $data['has_map'] : null;
        $this->container['is_accessible_for_free'] = isset($data['is_accessible_for_free']) ? $data['is_accessible_for_free'] : null;
        $this->container['maximum_attendee_capacity'] = isset($data['maximum_attendee_capacity']) ? $data['maximum_attendee_capacity'] : null;
        $this->container['opening_hours_specification'] = isset($data['opening_hours_specification']) ? $data['opening_hours_specification'] : null;
        $this->container['photo'] = isset($data['photo']) ? $data['photo'] : null;
        $this->container['public_access'] = isset($data['public_access']) ? $data['public_access'] : null;
        $this->container['smoking_allowed'] = isset($data['smoking_allowed']) ? $data['smoking_allowed'] : null;
        $this->container['source'] = isset($data['source']) ? $data['source'] : null;
        $this->container['special_opening_hours_specification'] = isset($data['special_opening_hours_specification']) ? $data['special_opening_hours_specification'] : null;
        $this->container['telephone'] = isset($data['telephone']) ? $data['telephone'] : null;
        $this->container['tourist_type'] = isset($data['tourist_type']) ? $data['tourist_type'] : null;
        $this->container['additional_property'] = isset($data['additional_property']) ? $data['additional_property'] : null;
        $this->container['geo_shape'] = isset($data['geo_shape']) ? $data['geo_shape'] : null;
        $this->container['cc'] = isset($data['cc']) ? $data['cc'] : null;
        $this->container['located'] = isset($data['located']) ? $data['located'] : null;
        $this->container['copyright'] = isset($data['copyright']) ? $data['copyright'] : null;
        $this->container['detailed_information'] = isset($data['detailed_information']) ? $data['detailed_information'] : null;
        $this->container['title_teaser'] = isset($data['title_teaser']) ? $data['title_teaser'] : null;
        $this->container['text_teaser'] = isset($data['text_teaser']) ? $data['text_teaser'] : null;
        $this->container['public_transport'] = isset($data['public_transport']) ? $data['public_transport'] : null;
        $this->container['getting_there'] = isset($data['getting_there']) ? $data['getting_there'] : null;
        $this->container['parking'] = isset($data['parking']) ? $data['parking'] : null;
        $this->container['directions'] = isset($data['directions']) ? $data['directions'] : null;
        $this->container['fees'] = isset($data['fees']) ? $data['fees'] : null;
        $this->container['zurichcard'] = isset($data['zurichcard']) ? $data['zurichcard'] : null;
        $this->container['zurichcard_description'] = isset($data['zurichcard_description']) ? $data['zurichcard_description'] : null;
        $this->container['osm_id'] = isset($data['osm_id']) ? $data['osm_id'] : null;
        $this->container['aggregate_rating'] = isset($data['aggregate_rating']) ? $data['aggregate_rating'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['opening_hours'] = isset($data['opening_hours']) ? $data['opening_hours'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['contained_in_place'] = isset($data['contained_in_place']) ? $data['contained_in_place'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['identifier'] = isset($data['identifier']) ? $data['identifier'] : null;
        $this->container['datasource'] = isset($data['datasource']) ? $data['datasource'] : null;
        $this->container['data_governance'] = isset($data['data_governance']) ? $data['data_governance'] : null;
        $this->container['alternate_name'] = isset($data['alternate_name']) ? $data['alternate_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['disambiguating_description'] = isset($data['disambiguating_description']) ? $data['disambiguating_description'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['same_as'] = isset($data['same_as']) ? $data['same_as'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['additional_type'] = isset($data['additional_type']) ? $data['additional_type'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['labels'] = isset($data['labels']) ? $data['labels'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets winter_activity
     *
     * @return bool
     */
    public function getWinterActivity()
    {
        return $this->container['winter_activity'];
    }

    /**
     * Sets winter_activity
     *
     * @param bool $winter_activity winter_activity
     *
     * @return $this
     */
    public function setWinterActivity($winter_activity)
    {
        $this->container['winter_activity'] = $winter_activity;

        return $this;
    }

    /**
     * Gets length
     *
     * @return double
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param double $length length
     *
     * @return $this
     */
    public function setLength($length)
    {
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets time
     *
     * @return int
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param int $time time
     *
     * @return $this
     */
    public function setTime($time)
    {
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets elevation_json
     *
     * @return object
     */
    public function getElevationJson()
    {
        return $this->container['elevation_json'];
    }

    /**
     * Sets elevation_json
     *
     * @param object $elevation_json elevation_json
     *
     * @return $this
     */
    public function setElevationJson($elevation_json)
    {
        $this->container['elevation_json'] = $elevation_json;

        return $this;
    }

    /**
     * Gets rating_json
     *
     * @return object
     */
    public function getRatingJson()
    {
        return $this->container['rating_json'];
    }

    /**
     * Sets rating_json
     *
     * @param object $rating_json rating_json
     *
     * @return $this
     */
    public function setRatingJson($rating_json)
    {
        $this->container['rating_json'] = $rating_json;

        return $this;
    }

    /**
     * Gets season_json
     *
     * @return object
     */
    public function getSeasonJson()
    {
        return $this->container['season_json'];
    }

    /**
     * Sets season_json
     *
     * @param object $season_json season_json
     *
     * @return $this
     */
    public function setSeasonJson($season_json)
    {
        $this->container['season_json'] = $season_json;

        return $this;
    }

    /**
     * Gets difficulties_json
     *
     * @return object
     */
    public function getDifficultiesJson()
    {
        return $this->container['difficulties_json'];
    }

    /**
     * Sets difficulties_json
     *
     * @param object $difficulties_json difficulties_json
     *
     * @return $this
     */
    public function setDifficultiesJson($difficulties_json)
    {
        $this->container['difficulties_json'] = $difficulties_json;

        return $this;
    }

    /**
     * Gets exposition_json
     *
     * @return object
     */
    public function getExpositionJson()
    {
        return $this->container['exposition_json'];
    }

    /**
     * Sets exposition_json
     *
     * @param object $exposition_json exposition_json
     *
     * @return $this
     */
    public function setExpositionJson($exposition_json)
    {
        $this->container['exposition_json'] = $exposition_json;

        return $this;
    }

    /**
     * Gets risk_potential
     *
     * @return int
     */
    public function getRiskPotential()
    {
        return $this->container['risk_potential'];
    }

    /**
     * Sets risk_potential
     *
     * @param int $risk_potential risk_potential
     *
     * @return $this
     */
    public function setRiskPotential($risk_potential)
    {
        $this->container['risk_potential'] = $risk_potential;

        return $this;
    }

    /**
     * Gets titles
     *
     * @return string
     */
    public function getTitles()
    {
        return $this->container['titles'];
    }

    /**
     * Sets titles
     *
     * @param string $titles titles
     *
     * @return $this
     */
    public function setTitles($titles)
    {
        $this->container['titles'] = $titles;

        return $this;
    }

    /**
     * Gets starting_point_description
     *
     * @return string
     */
    public function getStartingPointDescription()
    {
        return $this->container['starting_point_description'];
    }

    /**
     * Sets starting_point_description
     *
     * @param string $starting_point_description starting_point_description
     *
     * @return $this
     */
    public function setStartingPointDescription($starting_point_description)
    {
        $this->container['starting_point_description'] = $starting_point_description;

        return $this;
    }

    /**
     * Gets safety_guidelines
     *
     * @return string
     */
    public function getSafetyGuidelines()
    {
        return $this->container['safety_guidelines'];
    }

    /**
     * Sets safety_guidelines
     *
     * @param string $safety_guidelines safety_guidelines
     *
     * @return $this
     */
    public function setSafetyGuidelines($safety_guidelines)
    {
        $this->container['safety_guidelines'] = $safety_guidelines;

        return $this;
    }

    /**
     * Gets equipment
     *
     * @return string
     */
    public function getEquipment()
    {
        return $this->container['equipment'];
    }

    /**
     * Sets equipment
     *
     * @param string $equipment equipment
     *
     * @return $this
     */
    public function setEquipment($equipment)
    {
        $this->container['equipment'] = $equipment;

        return $this;
    }

    /**
     * Gets tip
     *
     * @return string
     */
    public function getTip()
    {
        return $this->container['tip'];
    }

    /**
     * Sets tip
     *
     * @param string $tip tip
     *
     * @return $this
     */
    public function setTip($tip)
    {
        $this->container['tip'] = $tip;

        return $this;
    }

    /**
     * Gets additional_information
     *
     * @return string
     */
    public function getAdditionalInformation()
    {
        return $this->container['additional_information'];
    }

    /**
     * Sets additional_information
     *
     * @param string $additional_information additional_information
     *
     * @return $this
     */
    public function setAdditionalInformation($additional_information)
    {
        $this->container['additional_information'] = $additional_information;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return string
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param string $destination destination
     *
     * @return $this
     */
    public function setDestination($destination)
    {
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets track_signage
     *
     * @return string
     */
    public function getTrackSignage()
    {
        return $this->container['track_signage'];
    }

    /**
     * Sets track_signage
     *
     * @param string $track_signage track_signage
     *
     * @return $this
     */
    public function setTrackSignage($track_signage)
    {
        $this->container['track_signage'] = $track_signage;

        return $this;
    }

    /**
     * Gets literature
     *
     * @return string
     */
    public function getLiterature()
    {
        return $this->container['literature'];
    }

    /**
     * Sets literature
     *
     * @param string $literature literature
     *
     * @return $this
     */
    public function setLiterature($literature)
    {
        $this->container['literature'] = $literature;

        return $this;
    }

    /**
     * Gets maps
     *
     * @return string
     */
    public function getMaps()
    {
        return $this->container['maps'];
    }

    /**
     * Sets maps
     *
     * @param string $maps maps
     *
     * @return $this
     */
    public function setMaps($maps)
    {
        $this->container['maps'] = $maps;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets available_language
     *
     * @return string[]
     */
    public function getAvailableLanguage()
    {
        return $this->container['available_language'];
    }

    /**
     * Sets available_language
     *
     * @param string[] $available_language available_language
     *
     * @return $this
     */
    public function setAvailableLanguage($available_language)
    {
        $this->container['available_language'] = $available_language;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddress
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddress $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets fax_number
     *
     * @return string
     */
    public function getFaxNumber()
    {
        return $this->container['fax_number'];
    }

    /**
     * Sets fax_number
     *
     * @param string $fax_number fax_number
     *
     * @return $this
     */
    public function setFaxNumber($fax_number)
    {
        $this->container['fax_number'] = $fax_number;

        return $this;
    }

    /**
     * Gets geo
     *
     * @return \Swagger\Client\Model\AdministrativeAreaGeo
     */
    public function getGeo()
    {
        return $this->container['geo'];
    }

    /**
     * Sets geo
     *
     * @param \Swagger\Client\Model\AdministrativeAreaGeo $geo geo
     *
     * @return $this
     */
    public function setGeo($geo)
    {
        $this->container['geo'] = $geo;

        return $this;
    }

    /**
     * Gets has_map
     *
     * @return string
     */
    public function getHasMap()
    {
        return $this->container['has_map'];
    }

    /**
     * Sets has_map
     *
     * @param string $has_map has_map
     *
     * @return $this
     */
    public function setHasMap($has_map)
    {
        $this->container['has_map'] = $has_map;

        return $this;
    }

    /**
     * Gets is_accessible_for_free
     *
     * @return bool
     */
    public function getIsAccessibleForFree()
    {
        return $this->container['is_accessible_for_free'];
    }

    /**
     * Sets is_accessible_for_free
     *
     * @param bool $is_accessible_for_free is_accessible_for_free
     *
     * @return $this
     */
    public function setIsAccessibleForFree($is_accessible_for_free)
    {
        $this->container['is_accessible_for_free'] = $is_accessible_for_free;

        return $this;
    }

    /**
     * Gets maximum_attendee_capacity
     *
     * @return int
     */
    public function getMaximumAttendeeCapacity()
    {
        return $this->container['maximum_attendee_capacity'];
    }

    /**
     * Sets maximum_attendee_capacity
     *
     * @param int $maximum_attendee_capacity maximum_attendee_capacity
     *
     * @return $this
     */
    public function setMaximumAttendeeCapacity($maximum_attendee_capacity)
    {
        $this->container['maximum_attendee_capacity'] = $maximum_attendee_capacity;

        return $this;
    }

    /**
     * Gets opening_hours_specification
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressHoursAvailable[]
     */
    public function getOpeningHoursSpecification()
    {
        return $this->container['opening_hours_specification'];
    }

    /**
     * Sets opening_hours_specification
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressHoursAvailable[] $opening_hours_specification opening_hours_specification
     *
     * @return $this
     */
    public function setOpeningHoursSpecification($opening_hours_specification)
    {
        $this->container['opening_hours_specification'] = $opening_hours_specification;

        return $this;
    }

    /**
     * Gets photo
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressImage[]
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressImage[] $photo photo
     *
     * @return $this
     */
    public function setPhoto($photo)
    {
        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets public_access
     *
     * @return bool
     */
    public function getPublicAccess()
    {
        return $this->container['public_access'];
    }

    /**
     * Sets public_access
     *
     * @param bool $public_access public_access
     *
     * @return $this
     */
    public function setPublicAccess($public_access)
    {
        $this->container['public_access'] = $public_access;

        return $this;
    }

    /**
     * Gets smoking_allowed
     *
     * @return bool
     */
    public function getSmokingAllowed()
    {
        return $this->container['smoking_allowed'];
    }

    /**
     * Sets smoking_allowed
     *
     * @param bool $smoking_allowed smoking_allowed
     *
     * @return $this
     */
    public function setSmokingAllowed($smoking_allowed)
    {
        $this->container['smoking_allowed'] = $smoking_allowed;

        return $this;
    }

    /**
     * Gets source
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressSource
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressSource $source source
     *
     * @return $this
     */
    public function setSource($source)
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets special_opening_hours_specification
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressHoursAvailable[]
     */
    public function getSpecialOpeningHoursSpecification()
    {
        return $this->container['special_opening_hours_specification'];
    }

    /**
     * Sets special_opening_hours_specification
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressHoursAvailable[] $special_opening_hours_specification special_opening_hours_specification
     *
     * @return $this
     */
    public function setSpecialOpeningHoursSpecification($special_opening_hours_specification)
    {
        $this->container['special_opening_hours_specification'] = $special_opening_hours_specification;

        return $this;
    }

    /**
     * Gets telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->container['telephone'];
    }

    /**
     * Sets telephone
     *
     * @param string $telephone telephone
     *
     * @return $this
     */
    public function setTelephone($telephone)
    {
        $this->container['telephone'] = $telephone;

        return $this;
    }

    /**
     * Gets tourist_type
     *
     * @return string
     */
    public function getTouristType()
    {
        return $this->container['tourist_type'];
    }

    /**
     * Sets tourist_type
     *
     * @param string $tourist_type tourist_type
     *
     * @return $this
     */
    public function setTouristType($tourist_type)
    {
        $this->container['tourist_type'] = $tourist_type;

        return $this;
    }

    /**
     * Gets additional_property
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAdditionalProperty[]
     */
    public function getAdditionalProperty()
    {
        return $this->container['additional_property'];
    }

    /**
     * Sets additional_property
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAdditionalProperty[] $additional_property additional_property
     *
     * @return $this
     */
    public function setAdditionalProperty($additional_property)
    {
        $this->container['additional_property'] = $additional_property;

        return $this;
    }

    /**
     * Gets geo_shape
     *
     * @return \Swagger\Client\Model\AdministrativeAreaGeoShape
     */
    public function getGeoShape()
    {
        return $this->container['geo_shape'];
    }

    /**
     * Sets geo_shape
     *
     * @param \Swagger\Client\Model\AdministrativeAreaGeoShape $geo_shape geo_shape
     *
     * @return $this
     */
    public function setGeoShape($geo_shape)
    {
        $this->container['geo_shape'] = $geo_shape;

        return $this;
    }

    /**
     * Gets cc
     *
     * @return string
     */
    public function getCc()
    {
        return $this->container['cc'];
    }

    /**
     * Sets cc
     *
     * @param string $cc cc
     *
     * @return $this
     */
    public function setCc($cc)
    {
        $this->container['cc'] = $cc;

        return $this;
    }

    /**
     * Gets located
     *
     * @return string[]
     */
    public function getLocated()
    {
        return $this->container['located'];
    }

    /**
     * Sets located
     *
     * @param string[] $located located
     *
     * @return $this
     */
    public function setLocated($located)
    {
        $this->container['located'] = $located;

        return $this;
    }

    /**
     * Gets copyright
     *
     * @return string
     */
    public function getCopyright()
    {
        return $this->container['copyright'];
    }

    /**
     * Sets copyright
     *
     * @param string $copyright copyright
     *
     * @return $this
     */
    public function setCopyright($copyright)
    {
        $this->container['copyright'] = $copyright;

        return $this;
    }

    /**
     * Gets detailed_information
     *
     * @return string[]
     */
    public function getDetailedInformation()
    {
        return $this->container['detailed_information'];
    }

    /**
     * Sets detailed_information
     *
     * @param string[] $detailed_information detailed_information
     *
     * @return $this
     */
    public function setDetailedInformation($detailed_information)
    {
        $this->container['detailed_information'] = $detailed_information;

        return $this;
    }

    /**
     * Gets title_teaser
     *
     * @return string
     */
    public function getTitleTeaser()
    {
        return $this->container['title_teaser'];
    }

    /**
     * Sets title_teaser
     *
     * @param string $title_teaser title_teaser
     *
     * @return $this
     */
    public function setTitleTeaser($title_teaser)
    {
        $this->container['title_teaser'] = $title_teaser;

        return $this;
    }

    /**
     * Gets text_teaser
     *
     * @return string
     */
    public function getTextTeaser()
    {
        return $this->container['text_teaser'];
    }

    /**
     * Sets text_teaser
     *
     * @param string $text_teaser text_teaser
     *
     * @return $this
     */
    public function setTextTeaser($text_teaser)
    {
        $this->container['text_teaser'] = $text_teaser;

        return $this;
    }

    /**
     * Gets public_transport
     *
     * @return string
     */
    public function getPublicTransport()
    {
        return $this->container['public_transport'];
    }

    /**
     * Sets public_transport
     *
     * @param string $public_transport public_transport
     *
     * @return $this
     */
    public function setPublicTransport($public_transport)
    {
        $this->container['public_transport'] = $public_transport;

        return $this;
    }

    /**
     * Gets getting_there
     *
     * @return string
     */
    public function getGettingThere()
    {
        return $this->container['getting_there'];
    }

    /**
     * Sets getting_there
     *
     * @param string $getting_there getting_there
     *
     * @return $this
     */
    public function setGettingThere($getting_there)
    {
        $this->container['getting_there'] = $getting_there;

        return $this;
    }

    /**
     * Gets parking
     *
     * @return string
     */
    public function getParking()
    {
        return $this->container['parking'];
    }

    /**
     * Sets parking
     *
     * @param string $parking parking
     *
     * @return $this
     */
    public function setParking($parking)
    {
        $this->container['parking'] = $parking;

        return $this;
    }

    /**
     * Gets directions
     *
     * @return string
     */
    public function getDirections()
    {
        return $this->container['directions'];
    }

    /**
     * Sets directions
     *
     * @param string $directions directions
     *
     * @return $this
     */
    public function setDirections($directions)
    {
        $this->container['directions'] = $directions;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return string
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param string $fees fees
     *
     * @return $this
     */
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets zurichcard
     *
     * @return string
     */
    public function getZurichcard()
    {
        return $this->container['zurichcard'];
    }

    /**
     * Sets zurichcard
     *
     * @param string $zurichcard zurichcard
     *
     * @return $this
     */
    public function setZurichcard($zurichcard)
    {
        $this->container['zurichcard'] = $zurichcard;

        return $this;
    }

    /**
     * Gets zurichcard_description
     *
     * @return string
     */
    public function getZurichcardDescription()
    {
        return $this->container['zurichcard_description'];
    }

    /**
     * Sets zurichcard_description
     *
     * @param string $zurichcard_description zurichcard_description
     *
     * @return $this
     */
    public function setZurichcardDescription($zurichcard_description)
    {
        $this->container['zurichcard_description'] = $zurichcard_description;

        return $this;
    }

    /**
     * Gets osm_id
     *
     * @return string
     */
    public function getOsmId()
    {
        return $this->container['osm_id'];
    }

    /**
     * Sets osm_id
     *
     * @param string $osm_id osm_id
     *
     * @return $this
     */
    public function setOsmId($osm_id)
    {
        $this->container['osm_id'] = $osm_id;

        return $this;
    }

    /**
     * Gets aggregate_rating
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAggregateRating
     */
    public function getAggregateRating()
    {
        return $this->container['aggregate_rating'];
    }

    /**
     * Sets aggregate_rating
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAggregateRating $aggregate_rating aggregate_rating
     *
     * @return $this
     */
    public function setAggregateRating($aggregate_rating)
    {
        $this->container['aggregate_rating'] = $aggregate_rating;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return string
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param string $opening_hours opening_hours
     *
     * @return $this
     */
    public function setOpeningHours($opening_hours)
    {
        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressLabels[]
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressLabels[] $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets contained_in_place
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressLabels[]
     */
    public function getContainedInPlace()
    {
        return $this->container['contained_in_place'];
    }

    /**
     * Sets contained_in_place
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressLabels[] $contained_in_place contained_in_place
     *
     * @return $this
     */
    public function setContainedInPlace($contained_in_place)
    {
        $this->container['contained_in_place'] = $contained_in_place;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return string
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string $identifier identifier
     *
     * @return $this
     */
    public function setIdentifier($identifier)
    {
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets datasource
     *
     * @return string
     */
    public function getDatasource()
    {
        return $this->container['datasource'];
    }

    /**
     * Sets datasource
     *
     * @param string $datasource datasource
     *
     * @return $this
     */
    public function setDatasource($datasource)
    {
        $this->container['datasource'] = $datasource;

        return $this;
    }

    /**
     * Gets data_governance
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressImageDataGovernance
     */
    public function getDataGovernance()
    {
        return $this->container['data_governance'];
    }

    /**
     * Sets data_governance
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressImageDataGovernance $data_governance data_governance
     *
     * @return $this
     */
    public function setDataGovernance($data_governance)
    {
        $this->container['data_governance'] = $data_governance;

        return $this;
    }

    /**
     * Gets alternate_name
     *
     * @return string
     */
    public function getAlternateName()
    {
        return $this->container['alternate_name'];
    }

    /**
     * Sets alternate_name
     *
     * @param string $alternate_name alternate_name
     *
     * @return $this
     */
    public function setAlternateName($alternate_name)
    {
        $this->container['alternate_name'] = $alternate_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets disambiguating_description
     *
     * @return string
     */
    public function getDisambiguatingDescription()
    {
        return $this->container['disambiguating_description'];
    }

    /**
     * Sets disambiguating_description
     *
     * @param string $disambiguating_description disambiguating_description
     *
     * @return $this
     */
    public function setDisambiguatingDescription($disambiguating_description)
    {
        $this->container['disambiguating_description'] = $disambiguating_description;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressImage
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressImage $image image
     *
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets same_as
     *
     * @return string
     */
    public function getSameAs()
    {
        return $this->container['same_as'];
    }

    /**
     * Sets same_as
     *
     * @param string $same_as same_as
     *
     * @return $this
     */
    public function setSameAs($same_as)
    {
        $this->container['same_as'] = $same_as;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets additional_type
     *
     * @return string
     */
    public function getAdditionalType()
    {
        return $this->container['additional_type'];
    }

    /**
     * Sets additional_type
     *
     * @param string $additional_type additional_type
     *
     * @return $this
     */
    public function setAdditionalType($additional_type)
    {
        $this->container['additional_type'] = $additional_type;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressImageDataGovernanceSourceLink[]
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressImageDataGovernanceSourceLink[] $links links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \Swagger\Client\Model\AdministrativeAreaAddressLabels[]
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \Swagger\Client\Model\AdministrativeAreaAddressLabels[] $labels labels
     *
     * @return $this
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
