<?php
/**
 * AdministrativeAreaAddressImageDataGovernanceSourceLogoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST
 *
 * Infocenter-TEST
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdministrativeAreaAddressImageDataGovernanceSourceLogoTest Class Doc Comment
 *
 * @category    Class
 * @description AdministrativeAreaAddressImageDataGovernanceSourceLogo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdministrativeAreaAddressImageDataGovernanceSourceLogoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdministrativeAreaAddressImageDataGovernanceSourceLogo"
     */
    public function testAdministrativeAreaAddressImageDataGovernanceSourceLogo()
    {
    }

    /**
     * Test attribute "caption"
     */
    public function testPropertyCaption()
    {
    }

    /**
     * Test attribute "content_url"
     */
    public function testPropertyContentUrl()
    {
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }
}
