<?php
/**
 * DsAccommodationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsAccommodationTest Class Doc Comment
 *
 * @category    Class
 * @description DsAccommodation
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsAccommodationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsAccommodation"
     */
    public function testDsAccommodation()
    {
    }

    /**
     * Test attribute "accommodation_category"
     */
    public function testPropertyAccommodationCategory()
    {
    }

    /**
     * Test attribute "floor_level"
     */
    public function testPropertyFloorLevel()
    {
    }

    /**
     * Test attribute "permitted_usage"
     */
    public function testPropertyPermittedUsage()
    {
    }

    /**
     * Test attribute "bed"
     */
    public function testPropertyBed()
    {
    }

    /**
     * Test attribute "floor_size"
     */
    public function testPropertyFloorSize()
    {
    }

    /**
     * Test attribute "number_of_bedrooms"
     */
    public function testPropertyNumberOfBedrooms()
    {
    }

    /**
     * Test attribute "number_of_rooms"
     */
    public function testPropertyNumberOfRooms()
    {
    }

    /**
     * Test attribute "number_of_bathrooms"
     */
    public function testPropertyNumberOfBathrooms()
    {
    }

    /**
     * Test attribute "occupancy"
     */
    public function testPropertyOccupancy()
    {
    }

    /**
     * Test attribute "lease_length"
     */
    public function testPropertyLeaseLength()
    {
    }

    /**
     * Test attribute "pets_allowed"
     */
    public function testPropertyPetsAllowed()
    {
    }

    /**
     * Test attribute "year_built"
     */
    public function testPropertyYearBuilt()
    {
    }

    /**
     * Test attribute "contained_in_lodging_business"
     */
    public function testPropertyContainedInLodgingBusiness()
    {
    }

    /**
     * Test attribute "available_language"
     */
    public function testPropertyAvailableLanguage()
    {
    }

    /**
     * Test attribute "branch_code"
     */
    public function testPropertyBranchCode()
    {
    }

    /**
     * Test attribute "slogan"
     */
    public function testPropertySlogan()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "fax_number"
     */
    public function testPropertyFaxNumber()
    {
    }

    /**
     * Test attribute "geo"
     */
    public function testPropertyGeo()
    {
    }

    /**
     * Test attribute "has_map"
     */
    public function testPropertyHasMap()
    {
    }

    /**
     * Test attribute "is_accessible_for_free"
     */
    public function testPropertyIsAccessibleForFree()
    {
    }

    /**
     * Test attribute "maximum_attendee_capacity"
     */
    public function testPropertyMaximumAttendeeCapacity()
    {
    }

    /**
     * Test attribute "opening_hours_specification"
     */
    public function testPropertyOpeningHoursSpecification()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "photo"
     */
    public function testPropertyPhoto()
    {
    }

    /**
     * Test attribute "public_access"
     */
    public function testPropertyPublicAccess()
    {
    }

    /**
     * Test attribute "smoking_allowed"
     */
    public function testPropertySmokingAllowed()
    {
    }

    /**
     * Test attribute "special_opening_hours_specification"
     */
    public function testPropertySpecialOpeningHoursSpecification()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "tourist_type"
     */
    public function testPropertyTouristType()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "state_timestamp"
     */
    public function testPropertyStateTimestamp()
    {
    }

    /**
     * Test attribute "geo_shape"
     */
    public function testPropertyGeoShape()
    {
    }

    /**
     * Test attribute "located"
     */
    public function testPropertyLocated()
    {
    }

    /**
     * Test attribute "copyright_notice"
     */
    public function testPropertyCopyrightNotice()
    {
    }

    /**
     * Test attribute "copyright"
     */
    public function testPropertyCopyright()
    {
    }

    /**
     * Test attribute "detailed_information"
     */
    public function testPropertyDetailedInformation()
    {
    }

    /**
     * Test attribute "title_teaser"
     */
    public function testPropertyTitleTeaser()
    {
    }

    /**
     * Test attribute "text_teaser"
     */
    public function testPropertyTextTeaser()
    {
    }

    /**
     * Test attribute "public_transport"
     */
    public function testPropertyPublicTransport()
    {
    }

    /**
     * Test attribute "getting_there"
     */
    public function testPropertyGettingThere()
    {
    }

    /**
     * Test attribute "parking"
     */
    public function testPropertyParking()
    {
    }

    /**
     * Test attribute "directions"
     */
    public function testPropertyDirections()
    {
    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {
    }

    /**
     * Test attribute "zurichcard"
     */
    public function testPropertyZurichcard()
    {
    }

    /**
     * Test attribute "zurichcard_description"
     */
    public function testPropertyZurichcardDescription()
    {
    }

    /**
     * Test attribute "osm_id"
     */
    public function testPropertyOsmId()
    {
    }

    /**
     * Test attribute "aggregate_rating"
     */
    public function testPropertyAggregateRating()
    {
    }

    /**
     * Test attribute "opening_hours"
     */
    public function testPropertyOpeningHours()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "contained_in_place"
     */
    public function testPropertyContainedInPlace()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "campaign_tag"
     */
    public function testPropertyCampaignTag()
    {
    }

    /**
     * Test attribute "profile_tag"
     */
    public function testPropertyProfileTag()
    {
    }

    /**
     * Test attribute "audio"
     */
    public function testPropertyAudio()
    {
    }

    /**
     * Test attribute "video"
     */
    public function testPropertyVideo()
    {
    }

    /**
     * Test attribute "review"
     */
    public function testPropertyReview()
    {
    }

    /**
     * Test attribute "robots"
     */
    public function testPropertyRobots()
    {
    }

    /**
     * Test attribute "accessibility"
     */
    public function testPropertyAccessibility()
    {
    }

    /**
     * Test attribute "award"
     */
    public function testPropertyAward()
    {
    }

    /**
     * Test attribute "located_at"
     */
    public function testPropertyLocatedAt()
    {
    }

    /**
     * Test attribute "amenity_feature"
     */
    public function testPropertyAmenityFeature()
    {
    }

    /**
     * Test attribute "variable_measured"
     */
    public function testPropertyVariableMeasured()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "removed"
     */
    public function testPropertyRemoved()
    {
    }

    /**
     * Test attribute "data_governance"
     */
    public function testPropertyDataGovernance()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "attachment"
     */
    public function testPropertyAttachment()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "available_data_language"
     */
    public function testPropertyAvailableDataLanguage()
    {
    }

    /**
     * Test attribute "auto_translated_data"
     */
    public function testPropertyAutoTranslatedData()
    {
    }

    /**
     * Test attribute "license"
     */
    public function testPropertyLicense()
    {
    }

    /**
     * Test attribute "type_name"
     */
    public function testPropertyTypeName()
    {
    }

    /**
     * Test attribute "alternate_name"
     */
    public function testPropertyAlternateName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "disambiguating_description"
     */
    public function testPropertyDisambiguatingDescription()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "same_as"
     */
    public function testPropertySameAs()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "potential_action"
     */
    public function testPropertyPotentialAction()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
