<?php
/**
 * DsAudioObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

/**
 * DsAudioObjectTest Class Doc Comment
 *
 * @category    Class
 * @description DsAudioObject
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsAudioObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsAudioObject"
     */
    public function testDsAudioObject()
    {
    }

    /**
     * Test attribute "caption"
     */
    public function testPropertyCaption()
    {
    }

    /**
     * Test attribute "content_size"
     */
    public function testPropertyContentSize()
    {
    }

    /**
     * Test attribute "content_url"
     */
    public function testPropertyContentUrl()
    {
    }

    /**
     * Test attribute "embed_url"
     */
    public function testPropertyEmbedUrl()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "content_reference_time"
     */
    public function testPropertyContentReferenceTime()
    {
    }

    /**
     * Test attribute "copyright_year"
     */
    public function testPropertyCopyrightYear()
    {
    }

    /**
     * Test attribute "encoding_format"
     */
    public function testPropertyEncodingFormat()
    {
    }

    /**
     * Test attribute "is_accessible_for_free"
     */
    public function testPropertyIsAccessibleForFree()
    {
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
    }

    /**
     * Test attribute "in_language"
     */
    public function testPropertyInLanguage()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "contained_in_place"
     */
    public function testPropertyContainedInPlace()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "campaign_tag"
     */
    public function testPropertyCampaignTag()
    {
    }

    /**
     * Test attribute "profile_tag"
     */
    public function testPropertyProfileTag()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "removed"
     */
    public function testPropertyRemoved()
    {
    }

    /**
     * Test attribute "data_governance"
     */
    public function testPropertyDataGovernance()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "available_data_language"
     */
    public function testPropertyAvailableDataLanguage()
    {
    }

    /**
     * Test attribute "auto_translated_data"
     */
    public function testPropertyAutoTranslatedData()
    {
    }

    /**
     * Test attribute "license"
     */
    public function testPropertyLicense()
    {
    }

    /**
     * Test attribute "alternate_name"
     */
    public function testPropertyAlternateName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "disambiguating_description"
     */
    public function testPropertyDisambiguatingDescription()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "same_as"
     */
    public function testPropertySameAs()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
