<?php
/**
 * DsFullSearchRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST
 *
 * Infocenter-TEST
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

/**
 * DsFullSearchRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsFullSearchRequest
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsFullSearchRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsFullSearchRequest"
     */
    public function testDsFullSearchRequest()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "contained_in_place"
     */
    public function testPropertyContainedInPlace()
    {
    }

    /**
     * Test attribute "address_locality"
     */
    public function testPropertyAddressLocality()
    {
    }

    /**
     * Test attribute "address_postal_code"
     */
    public function testPropertyAddressPostalCode()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "rating_condition"
     */
    public function testPropertyRatingCondition()
    {
    }

    /**
     * Test attribute "rating_difficulty"
     */
    public function testPropertyRatingDifficulty()
    {
    }

    /**
     * Test attribute "elevation_ascent"
     */
    public function testPropertyElevationAscent()
    {
    }

    /**
     * Test attribute "elevation_descent"
     */
    public function testPropertyElevationDescent()
    {
    }

    /**
     * Test attribute "elevation_min_altitude"
     */
    public function testPropertyElevationMinAltitude()
    {
    }

    /**
     * Test attribute "elevation_max_altitude"
     */
    public function testPropertyElevationMaxAltitude()
    {
    }

    /**
     * Test attribute "season"
     */
    public function testPropertySeason()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "datasource"
     */
    public function testPropertyDatasource()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "parent_type"
     */
    public function testPropertyParentType()
    {
    }

    /**
     * Test attribute "campaign_tag"
     */
    public function testPropertyCampaignTag()
    {
    }

    /**
     * Test attribute "facets"
     */
    public function testPropertyFacets()
    {
    }

    /**
     * Test attribute "search_text"
     */
    public function testPropertySearchText()
    {
    }

    /**
     * Test attribute "search_fields"
     */
    public function testPropertySearchFields()
    {
    }

    /**
     * Test attribute "select"
     */
    public function testPropertySelect()
    {
    }

    /**
     * Test attribute "current_page"
     */
    public function testPropertyCurrentPage()
    {
    }

    /**
     * Test attribute "results_per_page"
     */
    public function testPropertyResultsPerPage()
    {
    }

    /**
     * Test attribute "order_by"
     */
    public function testPropertyOrderBy()
    {
    }
}
