<?php
/**
 * DsListProductRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsListProductRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsListProductRequest
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsListProductRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsListProductRequest"
     */
    public function testDsListProductRequest()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "updated_since"
     */
    public function testPropertyUpdatedSince()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "area_served"
     */
    public function testPropertyAreaServed()
    {
    }

    /**
     * Test attribute "continuation_token"
     */
    public function testPropertyContinuationToken()
    {
    }

    /**
     * Test attribute "top"
     */
    public function testPropertyTop()
    {
    }

    /**
     * Test attribute "datasource"
     */
    public function testPropertyDatasource()
    {
    }

    /**
     * Test attribute "publish"
     */
    public function testPropertyPublish()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "include_count"
     */
    public function testPropertyIncludeCount()
    {
    }

    /**
     * Test attribute "identifiers"
     */
    public function testPropertyIdentifiers()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "contained_in_place"
     */
    public function testPropertyContainedInPlace()
    {
    }

    /**
     * Test attribute "partner_acronym"
     */
    public function testPropertyPartnerAcronym()
    {
    }

    /**
     * Test attribute "select"
     */
    public function testPropertySelect()
    {
    }

    /**
     * Test attribute "description_mode"
     */
    public function testPropertyDescriptionMode()
    {
    }

    /**
     * Test attribute "include_all_photos"
     */
    public function testPropertyIncludeAllPhotos()
    {
    }
}
