<?php
/**
 * DsPartnerSimplexLogoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsPartnerSimplexLogoTest Class Doc Comment
 *
 * @category    Class
 * @description DsPartnerSimplexLogo
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsPartnerSimplexLogoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsPartnerSimplexLogo"
     */
    public function testDsPartnerSimplexLogo()
    {
    }

    /**
     * Test attribute "content_url"
     */
    public function testPropertyContentUrl()
    {
    }

    /**
     * Test attribute "encoding_format"
     */
    public function testPropertyEncodingFormat()
    {
    }

    /**
     * Test attribute "in_language"
     */
    public function testPropertyInLanguage()
    {
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
