<?php
/**
 * DsResortFeatureSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

/**
 * DsResortFeatureSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description DsResortFeatureSummary
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsResortFeatureSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsResortFeatureSummary"
     */
    public function testDsResortFeatureSummary()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "opening_hours_specification"
     */
    public function testPropertyOpeningHoursSpecification()
    {
    }

    /**
     * Test attribute "min_elevation"
     */
    public function testPropertyMinElevation()
    {
    }

    /**
     * Test attribute "max_elevation"
     */
    public function testPropertyMaxElevation()
    {
    }

    /**
     * Test attribute "total_features"
     */
    public function testPropertyTotalFeatures()
    {
    }

    /**
     * Test attribute "total_features_open"
     */
    public function testPropertyTotalFeaturesOpen()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "report"
     */
    public function testPropertyReport()
    {
    }
}
