<?php
/**
 * DsTourSeasonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST-V2
 *
 * Infocenter API test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

/**
 * DsTourSeasonTest Class Doc Comment
 *
 * @category    Class
 * @description DsTourSeason
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsTourSeasonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsTourSeason"
     */
    public function testDsTourSeason()
    {
    }

    /**
     * Test attribute "jan"
     */
    public function testPropertyJan()
    {
    }

    /**
     * Test attribute "feb"
     */
    public function testPropertyFeb()
    {
    }

    /**
     * Test attribute "mar"
     */
    public function testPropertyMar()
    {
    }

    /**
     * Test attribute "apr"
     */
    public function testPropertyApr()
    {
    }

    /**
     * Test attribute "may"
     */
    public function testPropertyMay()
    {
    }

    /**
     * Test attribute "jun"
     */
    public function testPropertyJun()
    {
    }

    /**
     * Test attribute "jul"
     */
    public function testPropertyJul()
    {
    }

    /**
     * Test attribute "aug"
     */
    public function testPropertyAug()
    {
    }

    /**
     * Test attribute "sep"
     */
    public function testPropertySep()
    {
    }

    /**
     * Test attribute "oct"
     */
    public function testPropertyOct()
    {
    }

    /**
     * Test attribute "nov"
     */
    public function testPropertyNov()
    {
    }

    /**
     * Test attribute "dec"
     */
    public function testPropertyDec()
    {
    }
}
