<?php
/**
 * ScheduleStartTimeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Infocenter\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Infocenter-TEST
 *
 * Infocenter-TEST
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Infocenter\Client;

/**
 * ScheduleStartTimeTest Class Doc Comment
 *
 * @category    Class
 * @description ScheduleStartTime
 * @package     Infocenter\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleStartTimeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScheduleStartTime"
     */
    public function testScheduleStartTime()
    {
    }

    /**
     * Test attribute "ticks"
     */
    public function testPropertyTicks()
    {
    }

    /**
     * Test attribute "days"
     */
    public function testPropertyDays()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "milliseconds"
     */
    public function testPropertyMilliseconds()
    {
    }

    /**
     * Test attribute "minutes"
     */
    public function testPropertyMinutes()
    {
    }

    /**
     * Test attribute "seconds"
     */
    public function testPropertySeconds()
    {
    }

    /**
     * Test attribute "total_days"
     */
    public function testPropertyTotalDays()
    {
    }

    /**
     * Test attribute "total_hours"
     */
    public function testPropertyTotalHours()
    {
    }

    /**
     * Test attribute "total_milliseconds"
     */
    public function testPropertyTotalMilliseconds()
    {
    }

    /**
     * Test attribute "total_minutes"
     */
    public function testPropertyTotalMinutes()
    {
    }

    /**
     * Test attribute "total_seconds"
     */
    public function testPropertyTotalSeconds()
    {
    }
}
